export const FETCHING_DATA = "FETCHING_DATA";
export const GET_YOUTUBE_CONTENT = "GET_YOUTUBE_CONTENT";
export const GET_YOUTUBE_UPLOADS_PLAYLIST_ID = "GET_YOUTUBE_UPLOADS_PLAYLIST_ID";
export const PLAY_YOUTUBE_VIDEO = "PLAY_YOUTUBE_VIDEO";