export const FETCHING_YOUTUBE_DATA = "FETCHING_YOUTUBE_DATA";
export const GET_YOUTUBE_UPLOADS_PLAYLIST_ID = "GET_YOUTUBE_UPLOADS_PLAYLIST_ID";
export const GET_YOUTUBE_CONTENT = "GET_YOUTUBE_CONTENT";
export const PLAY_YOUTUBE_VIDEO = "PLAY_YOUTUBE_VIDEO";

export const FETCHING_VIMEO_DATA = "FETCHING_VIMEO_DATA";
export const GET_VIMEO_CONTENT = "GET_VIMEO_CONTENT";
export const PLAY_VIMEO_VIDEO = "PLAY_VIMEO_VIDEO";

export const SET_INSTAGRAM_AUTH_DATA = "SET_INSTAGRAM_AUTH_DATA";
export const FETCHING_INSTAGRAM_DATA = "FETCHING_INSTAGRAM_DATA";
export const GET_INSTAGRAM_CONTENT = "GET_INSTAGRAM_CONTENT";
export const GET_INSTAGRAM_VIDEO_EMBED = "GET_INSTAGRAM_VIDEO_EMBED";